import "./globals.css";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ficker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt">
      <body className={manrope.className}>
        <div className="h-12 bg-white"></div>
        {children}
      </body>
    </html>
  );
}
